### ISSUE TITLE
Double-encoded nsvlan_interfaces

### ISSUE THREAD

**Issue by rtollevik** [netscaler/terraform-provider-netscalersdx#40]
The nsvlan_interfaces string values in netscalersdx 0.2.0 appear to be double-encoded in the request sent to the netscaler.  

A terraform property like: 'nsvlan_interfaces = [ "0/1" ]' is sent on the "wire" as 'nsvlan_interfaces: [ "\\"0/1\\"" ]'.  And the netscaler responds with the error message 'Interface \\"0\/1\\" is not selected'.

**Comment by rohit-myali** [comment]
Hello @rtollevik 
We have looked this issue, We will update our provider and inform you. 

Thanks
