### ISSUE TITLE
Updation of 'vm_total_memory' parameter in VPX resource on SDX fails

### ISSUE THREAD

**Issue by ksashokumar** [netscaler/terraform-provider-netscalersdx#6]
1. Provisioned a VM on SDX with 'vm_total_memory' of 6144M.
2. After successful provisioning, updated the 'vm_total_memory' to 8192M.
3. At this point, I'm getting the below API error.
module.dut_provision[0].citrixsdx_provision_vpx.dut: Modifying... [id=8f031c9a-be4a-4589-9783-ba48af929a7c]
╷
**│ Error: failed: 400 Bad Request ({ "errorcode": 10014, "message": "Disabling untagged packets on interface 10\/7 is not allowed", "severity": "ERROR" })**
│
│   with module.dut_provision[0].citrixsdx_provision_vpx.dut,
│   on ../dut_sdx/main.tf line 1, in resource "citrixsdx_provision_vpx" "dut":
│    1: resource "citrixsdx_provision_vpx" "dut" {
│
╵

**Comment by rohit-myali** [comment]
This has been handled when we migrated our provider from terraform-sdk to terraform plugin framework.
