### ISSUE TITLE
[FEATURE REQUEST] support to set hypervisor_hostname

### ISSUE THREAD

**Issue by adc-nerd** [netscaler/terraform-provider-netscalersdx#76]
This is a request to add support of "current_hostname" ressource especially property "hypervisor_hostname".

API Reference is not up2date - https://developer-docs.netscaler.com/en-us/adc-sdx-nitro-api-reference/current-release/configuration/System/current_hostname.html

There are two properties "hostname" & "hypervisor_hostname".

**Comment by rohit-myali** [comment]
Hey @adc-nerd 
I see the above link for API docs, there is only one property named "hostname". There is no attribute named "hypervisor_hostname". Do you mean "hostname" itself?

**Comment by adc-nerd** [comment]
No - docs are not current. There is an attribute "hypervisor_hostname".
example GET response:
SVM GUI - Configuration - System -> Change Hostname
API-URL: https://my-sdx-svm/nitro/v1/config/current_hostname

`{
    "errorcode": 0,
    "message": "Done",
    "operation": "get",
    "resourceType": "current_hostname",
    "username": "-removed-",
    "tenant_name": "-removed-",
    "tenant_id": "-removed-",
    "resrc_total_count": 0,
    "resourceName": "",
    "current_hostname": [
        {
            "hypervisor_hostname": "my-sdx-xen",
            "hostname": "my-sdx-svm"
        }
    ]
}`
